behaviors:
  FlappyBirdAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 1.0e-4
      beta: 5.0e-4
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 4
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 20000
